backend:
  name: github
  repo: stableotto/hoteltrashcans
  branch: main
  base_url: https://hoteltrashcans.pages.dev
  auth_endpoint: /api/auth
  # The callback endpoint is handled by functions/api/callback.js

# Local backend for development (comment out for production)
# local_backend: true

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

# Custom editor components for better UX
editor:
  preview: false

collections:
  - name: "collections"
    label: "Trash Can Collections"
    folder: "src/content/collections"
    create: true
    slug: "{{slug}}-collection"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Specifications"
        name: "specifications"
        widget: "object"
        fields:
          - {label: "Dimensions", name: "dimensions", widget: "string"}
          - {label: "Capacity", name: "capacity", widget: "string"}
          - {label: "Designer", name: "designer", widget: "string", required: false}
      - {label: "Cover Image", name: "coverImage", widget: "image", hint: "Upload cover image"}
      - {label: "Hero Image", name: "heroImage", widget: "image", hint: "Upload hero image"}
      - {label: "Main Product Image", name: "mainProductImage", widget: "image", hint: "Upload main product image"}
      - label: "Color Variations"
        name: "colorVariations"
        widget: "list"
        fields:
          - label: "Name"
            name: "name"
            widget: "select"
            options: 
              - "Carbon"
              - "Parchment"
              - "Moss"
              - "Salmon"
              - "Merlot"
              - "Sage"
              - "White Burl"
              - "Topaz"
              - "Pearl White"
              - "Mink"
              - "Patina"
              - "Lava"
              - "Pewter"
              - "Mahogany"
              - "Carbon/Pewter"
              - "Lava/Mink"
              - "Patina/Sahara"
              - "Mink/Lava"
              - "Pearl White/Topaz"
              - "Topaz/Pewter"
            default: "Carbon"
          - {label: "Image", name: "image", widget: "image", hint: "Upload product image"}
          - {label: "Alt Text", name: "alt", widget: "string", hint: "Descriptive text for accessibility"}
      - {label: "Buy Now Link", name: "buyNowLink", widget: "string"}
      - {label: "Download PDF Link", name: "downloadPdfLink", widget: "string"}
      - {label: "Metal Options Link", name: "metalOptionsLink", widget: "string", required: false}
      - label: "SEO"
        name: "seo"
        widget: "object"
        required: false
        fields:
          - {label: "SEO Title", name: "title", widget: "string"}
          - {label: "SEO Description", name: "description", widget: "text"}
          - {label: "Keywords", name: "keywords", widget: "string", required: false} 